services:
  - type: web
    name: jaYomi
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        sync: false   # You fill this in after first deploy with your render URL
